### ISSUE TITLE
Fix typo in screenshot

### ISSUE THREAD

**Issue by becky000** [learn-co-students/sql-relational-databases-readme-v-000#1]
Manager is spelled incorrectly in the employees table screenshot. If you like I could make you a new png and attach here for upload.

**Comment by gj** [comment]
cc: @pletcher

**Comment by pletcher** [comment]
@becky000 that would be awesome -- could you actually add it as an issue on this repo: https://github.com/learn-co-curriculum/sql-relational-databases-readme ? (Or feel free to open a PR on that repo, too!)

**Comment by becky000** [comment]
Consider it done.
